import type { FormTemplate } from "../form-template-types";

/**
 * 座標は mm。
 * 1447×2048px の bbox キャリブレーションを mm 換算し、
 * プレビュー微調整 JSON（dx/dy/fontScale）を反映した値。
 */
export const hokkaidoMainTemplate: FormTemplate = {
  id: "hokkaido-main",
  version: "youshiki2-calibrated-v3",
  label: "猟銃用火薬類等譲受許可申請書（別記様式第2号）",
  sourceUrl: "https://www.police.pref.hokkaido.lg.jp/down_load/06/23.pdf",
  pageWidthMm: 210,
  pageHeightMm: 297,
  pages: [
    { imagePath: "/forms/acquisition-permit/hokkaido/png/main-youshiki2.pdf.png" },
    { imagePath: "/forms/acquisition-permit/hokkaido/png/main-youshiki2-back.pdf.png" },
  ],
  fields: [
    { id: "prefectureName", page: 0, x: 24.41, y: 42.59, width: 28, fontSize: 5 },
    {
      id: "applicationDateYear",
      page: 0,
      x: 128.73,
      y: 34.39,
      width: 16.69,
      height: 10.74,
      fontSize: 5,
      align: "right",
      verticalAlign: "center",
    },
    {
      id: "applicationDateMonth",
      page: 0,
      x: 151.61,
      y: 36.32,
      width: 8.93,
      height: 6.88,
      fontSize: 4.94,
      align: "right",
      verticalAlign: "center",
    },
    {
      id: "applicationDateDay",
      page: 0,
      x: 164.35,
      y: 36.46,
      width: 9.96,
      height: 6.6,
      fontSize: 4.94,
      align: "right",
      verticalAlign: "center",
    },
    {
      id: "ownerAddress",
      page: 0,
      x: 62.99,
      y: 51.79,
      width: 123.74,
      height: 16.91,
      fontSize: 4.94,
      verticalAlign: "center",
    },
    { id: "ownerFurigana", page: 0, x: 62.99, y: 69.75, width: 123.74, fontSize: 4.94 },
    {
      id: "ownerName",
      page: 0,
      x: 62.95,
      y: 78.48,
      width: 123.57,
      height: 18.13,
      fontSize: 8.47,
      verticalAlign: "center",
    },
    {
      id: "ownerBirthDateYear",
      page: 0,
      x: 65.37,
      y: 99.34,
      width: 33.38,
      fontSize: 4.94,
      align: "right",
    },
    {
      id: "ownerBirthDateMonth",
      page: 0,
      x: 105.16,
      y: 99.34,
      width: 17.42,
      fontSize: 4.94,
      align: "right",
    },
    {
      id: "ownerBirthDateDay",
      page: 0,
      x: 128.47,
      y: 99.34,
      width: 17.42,
      fontSize: 4.94,
      align: "right",
    },
    { id: "ownerPhone", page: 0, x: 63.03, y: 108.18, width: 123.76, height: 7.5, fontSize: 4.94 },
    { id: "ammoName", page: 0, x: 62.88, y: 126.29, width: 35.57, fontSize: 5.64, align: "center" },
    {
      id: "requestedQuantity",
      page: 0,
      x: 62.17,
      y: 135.28,
      width: 29.31,
      height: 8.52,
      fontSize: 4.94,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "gunType",
      page: 0,
      x: 87.08,
      y: 144.77,
      width: 42.75,
      height: 15.98,
      fontSize: 6.35,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "compatibleAmmunition",
      page: 0,
      x: 150.64,
      y: 144.73,
      width: 36.05,
      height: 15.7,
      fontSize: 6.35,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "currentHomeStock",
      page: 0,
      x: 62.99,
      y: 163.29,
      width: 123.24,
      height: 10.71,
      fontSize: 6.35,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "certificateTypeGunPossessionPermit",
      page: 0,
      x: 60.21,
      y: 172.22,
      width: 11.11,
      height: 10.51,
      fontSize: 4.94,
      align: "center",
      verticalAlign: "center",
      variant: "checkbox",
    },
    {
      id: "permitCertificateNumber",
      page: 0,
      x: 123.93,
      y: 179.8,
      width: 39.86,
      height: 13.5,
      fontSize: 5.64,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "permitPurpose",
      page: 0,
      x: 62.8,
      y: 201.27,
      width: 124.25,
      height: 7.12,
      fontSize: 4.94,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "validFromYear",
      page: 0,
      x: 62.43,
      y: 207.02,
      width: 13.13,
      height: 12.15,
      fontSize: 4.23,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "validFromMonth",
      page: 0,
      x: 79.75,
      y: 209.54,
      width: 9.85,
      height: 7.1,
      fontSize: 4.23,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "validFromDay",
      page: 0,
      x: 93.15,
      y: 209.23,
      width: 8.71,
      height: 7.72,
      fontSize: 4.23,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "validToYear",
      page: 0,
      x: 115.89,
      y: 206.14,
      width: 10.51,
      height: 13.9,
      fontSize: 4.23,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "validToMonth",
      page: 0,
      x: 131.38,
      y: 209.43,
      width: 7.98,
      height: 7.31,
      fontSize: 4.23,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "validToDay",
      page: 0,
      x: 145.01,
      y: 209.62,
      width: 8.71,
      height: 6.93,
      fontSize: 4.23,
      align: "center",
      verticalAlign: "center",
    },
    {
      id: "storageLocation",
      page: 0,
      x: 62.99,
      y: 217.56,
      width: 123.72,
      height: 13.4,
      fontSize: 4.94,
      verticalAlign: "center",
    },
  ],
};
