import type { FormTemplate } from "@/features/ammo-ledger/acquisition-permit-application/form-template/form-template-types";

export const hokkaidoForm6SupplementTemplate: FormTemplate = {
  id: "hokkaido-form6-supplement",
  version: "form6-supplement-initial-v1",
  label: "銃砲所持許可申請書 別紙（様式第6号）",
  sourceUrl: "https://www.police.pref.hokkaido.lg.jp/down_load/06/04.pdf",
  pageWidthMm: 210,
  pageHeightMm: 297,
  pages: [
    { imagePath: "/forms/gun-possession-permit/hokkaido/png/form6-supplement-front.png" },
    { imagePath: "/forms/gun-possession-permit/hokkaido/png/form6-supplement-back.png" },
  ],
  fields: [
    { id: "gunIndexLabel", page: 0, x: 24, y: 30, width: 20, fontSize: 5 },
    { id: "gunType", page: 0, x: 40, y: 52, width: 40, fontSize: 4.5 },
    { id: "gunModel", page: 0, x: 40, y: 60, width: 50, fontSize: 4.5 },
    { id: "gunNumber", page: 0, x: 40, y: 68, width: 50, fontSize: 4.5 },
    { id: "makerName", page: 0, x: 40, y: 76, width: 50, fontSize: 4 },
    { id: "totalLengthCm", page: 0, x: 120, y: 76, width: 20, fontSize: 4, align: "right" },
    { id: "barrelLengthCm", page: 0, x: 120, y: 84, width: 20, fontSize: 4, align: "right" },
    { id: "caliber", page: 0, x: 40, y: 92, width: 40, fontSize: 4 },
    {
      id: "purposeHunting",
      page: 0,
      x: 30,
      y: 118,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "purposeHarmfulBirdBeast",
      page: 0,
      x: 52,
      y: 118,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "purposeTargetShooting",
      page: 0,
      x: 82,
      y: 118,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    { id: "purposeDetail", page: 0, x: 110, y: 118, width: 70, fontSize: 4 },
    { id: "transferorAddress", page: 0, x: 40, y: 200, width: 120, fontSize: 4 },
    { id: "transferorName", page: 0, x: 40, y: 210, width: 80, fontSize: 4.5 },
    { id: "transferorPhone", page: 0, x: 130, y: 210, width: 40, fontSize: 4 },
    {
      id: "sameAsTransferConsent",
      page: 0,
      x: 30,
      y: 44,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
  ],
};
