/** 銃所持許可申請キャリブレーション画面のプレビュー用サンプル値（すべて架空） */
export const gunPermitCalibrationSampleFieldValues: Record<string, string> = {
  prefectureName: "北海道",
  applicationDateYear: "2026",
  applicationDateMonth: "6",
  applicationDateDay: "9",
  ownerRegisteredDomicile: "北海道札幌市",
  ownerAddress: "札幌市中央区北1条西2丁目 サンプルマンション101",
  ownerFurigana: "やまだ たろう",
  ownerName: "山田 太郎",
  ownerBirthDateYear: "1980",
  ownerBirthDateMonth: "1",
  ownerBirthDateDay: "15",
  ownerPhone: "09012345678",
  applicationCount: "1",
  existingPermitDate: "2024年4月1日",
  existingPermitNumber: "第12345号",
  lectureCertificateDate: "2026年3月1日",
  teachingCertificateDate: "2026年4月1日",
  skillLectureCertificateDate: "2026年5月1日",
  cohabitantNone: "",
  cohabitantCount: "2",
  pledgeDisqualification: "✓",
  pledgeHuntingDisqualification: "✓",
  omitCohabitantForm: "",
  omitCohabitantFormDate: "",
  omitMunicipalCertificate: "",
  omitMunicipalCertificateDate: "",
  omitResidentRecord: "",
  omitResidentRecordDate: "",
  omitResume: "",
  omitResumeDate: "",
  gunIndexLabel: "1／1",
  gunType: "散弾銃",
  gunModel: "単身ボルト式",
  gunNumber: "12345",
  makerName: "サンプル製造",
  totalLengthCm: "102",
  barrelLengthCm: "56",
  caliber: "12番",
  purposeHunting: "✓",
  purposeHarmfulBirdBeast: "",
  purposeTargetShooting: "",
  purposeDetail: "",
  transferorAddress: "札幌市中央区〇〇1-2-3",
  transferorName: "サンプル銃砲店",
  transferorPhone: "0111234567",
  sameAsTransferConsent: "✓",
  gunCategoryRifle: "",
  gunCategoryShotgun: "✓",
  gunCategoryAirRifle: "",
  gunCategoryHuntingRifleOther: "",
  permitNumber: "第12345号",
  permitDateYear: "2024",
  permitDateMonth: "4",
  permitDateDay: "1",
  hasCriminalRecordYes: "",
  hasCriminalRecordNo: "✓",
  hasTreatmentHistoryYes: "",
  hasTreatmentHistoryNo: "✓",
  criminalRecordDetail: "",
  periodFrom: "2010年4月",
  periodTo: "2020年3月",
  content: "サンプル株式会社",
  sameRegisteredDomicile: "✓",
  furigana: "やまだ はなこ",
  occupation: "会社員",
  name: "山田 花子",
  relationship: "妻",
  birthDateYear: "1982",
  birthDateMonth: "5",
  birthDateDay: "20",
};
