/** キャリブレーション画面のプレビュー用サンプル値（すべて架空） */
export const calibrationSampleFieldValues: Record<string, string> = {
  prefectureName: "北海道",
  applicationDateYear: "2026",
  applicationDateMonth: "4",
  applicationDateDay: "1",
  ownerAddress: "札幌市中央区北1条西2丁目 サンプルマンション101",
  ownerFurigana: "やまだ たろう",
  ownerName: "山田 太郎",
  ownerBirthDateYear: "1980",
  ownerBirthDateMonth: "1",
  ownerBirthDateDay: "1",
  ownerPhone: "09012345678",
  ammoName: "12番鳥散弾",
  requestedQuantity: "5000",
  gunType: "散弾銃",
  compatibleAmmunition: "12番",
  currentHomeStock: "12番鳥散弾 250個",
  certificateTypeGunPossessionPermit: "✓",
  permitCertificateNumber: "12345678901",
  permitPurpose: "標的射撃",
  validFromYear: "2026",
  validFromMonth: "4",
  validFromDay: "1",
  validToYear: "2027",
  validToMonth: "3",
  validToDay: "31",
  storageLocation: "自宅装弾ロッカー",
  planPurposeLabel: "標的射撃",
  year: "2026",
  month: "4",
  period: "上旬",
  purchaseQuantity: "2000",
  consumptionQuantity: "1500",
  locationCounterparty: "サンプル商店",
  locationRangeName: "〇〇射撃場",
  locationRangeAddress: "",
  memoTargetShooting: "✓",
  memoHunting: "",
  memoOther: "",
  memoOtherText: "",
};
