import type { FormTemplate } from "@/features/ammo-ledger/acquisition-permit-application/form-template/form-template-types";

export const hokkaidoForm9MainTemplate: FormTemplate = {
  id: "hokkaido-form9-main",
  version: "form9-initial-v1",
  label: "猟銃等所持許可更新申請書（様式第9号）",
  sourceUrl: "https://www.police.pref.hokkaido.lg.jp/down_load/06/05.pdf",
  pageWidthMm: 210,
  pageHeightMm: 297,
  pages: [{ imagePath: "/forms/gun-possession-permit/hokkaido/png/form9-main.png" }],
  fields: [
    { id: "prefectureName", page: 0, x: 24, y: 42, width: 28, fontSize: 5 },
    {
      id: "applicationDateYear",
      page: 0,
      x: 128,
      y: 34,
      width: 16,
      height: 8,
      fontSize: 5,
      align: "right",
      verticalAlign: "center",
    },
    {
      id: "applicationDateMonth",
      page: 0,
      x: 150,
      y: 34,
      width: 8,
      height: 8,
      fontSize: 5,
      align: "right",
      verticalAlign: "center",
    },
    {
      id: "applicationDateDay",
      page: 0,
      x: 163,
      y: 34,
      width: 8,
      height: 8,
      fontSize: 5,
      align: "right",
      verticalAlign: "center",
    },
    {
      id: "ownerRegisteredDomicile",
      page: 0,
      x: 62,
      y: 48,
      width: 120,
      height: 8,
      fontSize: 4.5,
      verticalAlign: "center",
    },
    {
      id: "ownerAddress",
      page: 0,
      x: 62,
      y: 56,
      width: 120,
      height: 12,
      fontSize: 4.5,
      verticalAlign: "center",
    },
    { id: "ownerFurigana", page: 0, x: 62, y: 70, width: 120, fontSize: 4.5 },
    {
      id: "ownerName",
      page: 0,
      x: 62,
      y: 78,
      width: 120,
      height: 14,
      fontSize: 8,
      verticalAlign: "center",
    },
    {
      id: "ownerBirthDateYear",
      page: 0,
      x: 65,
      y: 95,
      width: 30,
      fontSize: 4.5,
      align: "right",
    },
    {
      id: "ownerBirthDateMonth",
      page: 0,
      x: 102,
      y: 95,
      width: 14,
      fontSize: 4.5,
      align: "right",
    },
    {
      id: "ownerBirthDateDay",
      page: 0,
      x: 124,
      y: 95,
      width: 14,
      fontSize: 4.5,
      align: "right",
    },
    { id: "ownerPhone", page: 0, x: 62, y: 104, width: 80, fontSize: 4.5 },
    {
      id: "applicationCount",
      page: 0,
      x: 155,
      y: 112,
      width: 12,
      fontSize: 5,
      align: "right",
    },
    {
      id: "existingPermitDate",
      page: 0,
      x: 100,
      y: 128,
      width: 70,
      fontSize: 4,
    },
    {
      id: "existingPermitNumber",
      page: 0,
      x: 100,
      y: 136,
      width: 70,
      fontSize: 4,
    },
    {
      id: "skillLectureCertificateDate",
      page: 0,
      x: 100,
      y: 152,
      width: 70,
      fontSize: 4,
    },
    {
      id: "cohabitantNone",
      page: 0,
      x: 30,
      y: 168,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "cohabitantCount",
      page: 0,
      x: 52,
      y: 168,
      width: 10,
      fontSize: 5,
      align: "center",
    },
    {
      id: "pledgeDisqualification",
      page: 0,
      x: 30,
      y: 182,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "pledgeHuntingDisqualification",
      page: 0,
      x: 30,
      y: 194,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "omitCohabitantForm",
      page: 0,
      x: 30,
      y: 210,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "omitCohabitantFormDate",
      page: 0,
      x: 72,
      y: 210,
      width: 50,
      fontSize: 4,
    },
    {
      id: "omitResume",
      page: 0,
      x: 30,
      y: 218,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "omitResumeDate",
      page: 0,
      x: 72,
      y: 218,
      width: 50,
      fontSize: 4,
    },
  ],
};
