import type { FormTemplate } from "@/features/ammo-ledger/acquisition-permit-application/form-template/form-template-types";

export const hokkaidoResumeTemplate: FormTemplate = {
  id: "hokkaido-resume",
  version: "resume-initial-v1",
  label: "経歴書（別表第2の別記様式）",
  sourceUrl: "https://www.police.pref.hokkaido.lg.jp/down_load/06/01.pdf",
  pageWidthMm: 210,
  pageHeightMm: 297,
  pages: [
    { imagePath: "/forms/gun-possession-permit/hokkaido/png/resume-front.png" },
    { imagePath: "/forms/gun-possession-permit/hokkaido/png/resume-back.png" },
  ],
  fields: [
    {
      id: "applicationDateYear",
      page: 0,
      x: 150,
      y: 30,
      width: 12,
      fontSize: 4.5,
      align: "right",
    },
    {
      id: "applicationDateMonth",
      page: 0,
      x: 165,
      y: 30,
      width: 8,
      fontSize: 4.5,
      align: "right",
    },
    {
      id: "applicationDateDay",
      page: 0,
      x: 176,
      y: 30,
      width: 8,
      fontSize: 4.5,
      align: "right",
    },
    { id: "ownerName", page: 0, x: 120, y: 38, width: 70, fontSize: 6 },
    {
      id: "hasCriminalRecordYes",
      page: 1,
      x: 40,
      y: 170,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "hasCriminalRecordNo",
      page: 1,
      x: 55,
      y: 170,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "hasTreatmentHistoryYes",
      page: 1,
      x: 40,
      y: 190,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    {
      id: "hasTreatmentHistoryNo",
      page: 1,
      x: 55,
      y: 190,
      width: 6,
      height: 6,
      fontSize: 6,
      variant: "checkbox",
    },
    { id: "criminalRecordDetail", page: 1, x: 70, y: 178, width: 120, fontSize: 4 },
  ],
  repeatingRows: {
    startY: 52,
    rowHeight: 12,
    maxRowsPerPage: 5,
    columns: [
      { id: "periodFrom", x: 24, width: 28, fontSize: 4 },
      { id: "periodTo", x: 54, width: 28, fontSize: 4 },
      { id: "content", x: 86, width: 100, fontSize: 4 },
    ],
  },
};
