import type { FormTemplate } from "../form-template-types";

/** 別記様式第2号 別紙（r4-15 版）。PNG は申請書表と同じ左余白（20.1mm）に正規化済み。 */
export const ibarakiR7SupplementTemplate: FormTemplate = {
  id: "ibaraki-r7-supplement",
  version: "r4-15",
  label: "猟銃用火薬類等譲受許可申請書（別紙）",
  sourceUrl:
    "https://www.pref.ibaraki.jp/kenkei/a06_shinsei/swords_firearms/documents/juhotodoke-r4-15.pdf",
  pageWidthMm: 210,
  pageHeightMm: 297,
  pages: [{ imagePath: "/forms/acquisition-permit/ibaraki-r7/png/supplement-r4-15.pdf.png" }],
  fields: [
    {
      id: "planPurposeLabel",
      page: 0,
      x: 139.5,
      y: 31.7,
      width: 40.75,
      height: 6.9,
      fontSize: 4.94,
      align: "center",
      verticalAlign: "center",
    },
  ],
  repeatingRows: {
    startY: 50.92,
    rowHeight: 18.83,
    maxRowsPerPage: 10,
    columns: [
      {
        id: "year",
        x: 22.64,
        width: 13.04,
        fontSize: 4.94,
        align: "center",
        verticalAlign: "center",
        yOffset: -0.58,
        height: 7.89,
      },
      {
        id: "month",
        x: 20.62,
        width: 5.98,
        fontSize: 4.94,
        align: "center",
        verticalAlign: "center",
        yOffset: 8.93,
        height: 8.9,
      },
      {
        id: "period",
        x: 30.2,
        width: 5.65,
        fontSize: 4.94,
        align: "center",
        verticalAlign: "center",
        yOffset: 9.51,
        height: 7.74,
      },
      {
        id: "purchaseQuantity",
        x: 45.7,
        width: 18.77,
        fontSize: 5.64,
        align: "center",
        verticalAlign: "center",
        yOffset: -0.67,
        height: 18.19,
      },
      {
        id: "consumptionQuantity",
        x: 84.83,
        width: 18.99,
        fontSize: 5.64,
        align: "center",
        verticalAlign: "center",
        yOffset: -0.36,
        height: 17.57,
      },
      {
        id: "locationCounterparty",
        x: 118.03,
        width: 28.85,
        fontSize: 3.53,
        yOffset: -1.17,
        height: 6.34,
      },
      {
        id: "locationRangeName",
        x: 118.36,
        width: 22.1,
        fontSize: 3.53,
        yOffset: 3.99,
        height: 5.33,
      },
      {
        id: "locationRangeAddress",
        x: 118.16,
        width: 24.68,
        fontSize: 3.53,
        yOffset: 8.91,
        height: 5.83,
      },
      {
        id: "memoTargetShooting",
        x: 150.14,
        width: 6.94,
        fontSize: 3.53,
        align: "center",
        verticalAlign: "center",
        variant: "checkbox",
        yOffset: -2.12,
        height: 7.95,
      },
      {
        id: "memoHunting",
        x: 149.71,
        width: 7.52,
        fontSize: 3.53,
        align: "center",
        verticalAlign: "center",
        variant: "checkbox",
        yOffset: 2.78,
        height: 7.55,
      },
      {
        id: "memoOther",
        x: 150.05,
        width: 6.73,
        fontSize: 3.53,
        align: "center",
        verticalAlign: "center",
        variant: "checkbox",
        yOffset: 8.05,
        height: 6.41,
      },
      {
        id: "memoOtherText",
        x: 153.43,
        width: 33.62,
        fontSize: 1.94,
        align: "center",
        verticalAlign: "center",
        yOffset: 13.39,
        height: 5.19,
      },
    ],
  },
};
